### ISSUE TITLE
Error using OBS

### ISSUE THREAD

**Issue by CompositeLight** [josephdadams/TallyArbiter#142]
Just trying to use 2.0.5 on Mac. Added OBS as a source on the same Mac using the websocketsc plugin, and it connects fine (goes green in the sources list). But when I try to add the source to a device I get an error pop up, and subsequently I can't get OBS to tally. Here is the error:

A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: data is not defined
at Socket.<anonymous> (/Applications/TallyArbiter.app/Contents/Resources/app.asar/index.js:949:21)
at Socket.emit (events.js:315:20)
at Socket.emitUntyped (/Applications/TallyArbiter.app/Contents/Resources/app.asar/node_modules/socket.io/dist/typed-events.js:69:22)
at /Applications/TallyArbiter.app/Contents/Resources/app.asar/node_modules/socket.io/dist/socket.js:428:39
at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by josephdadams** [comment]
@hrueger it looks like line 949 could be commented out. I don’t see it being used

**Comment by hrueger** [comment]
[This line](https://github.com/josephdadams/TallyArbiter/blob/6e41b8d9f4ec2ce6fd69a4d7423b6ee04e8a3cc0/index.js#L949)? Yes, I think so. It was probably left over from merging two branches...

**Comment by JTF4** [comment]
#143 should fix this issue.

**Comment by JTF4** [comment]
@CompositeLight Version 2.0.6 is live and should fix your issue.

**Comment by CompositeLight** [comment]
Sorted - thank you! Amazing response time 🤩

**Comment by JTF4** [comment]
Your welcome! Glad it worked!
