### ISSUE TITLE
Installing on Raspberry Pi failed

### ISSUE THREAD

**Issue by peterfdej** [josephdadams/TallyArbiter#161]
### What happened?

I cannot install it again on a raspberry pi. Tried several version of NodeJs.
this is what is happening:
`pi@tallyarbiter:~/tallyarbiter $ sudo npm install --global tallyarbiter         npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.
/usr/bin/tallyarbiter -> /usr/lib/node_modules/tallyarbiter/bin/tallyarbiter

> fmerge@1.2.0 install /usr/lib/node_modules/tallyarbiter/node_modules/fmerge
> node install.js

internal/fs/utils.js:312
    throw err;
    ^

Error: EACCES: permission denied, open 'fmerge.min.js'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at Object.<anonymous> (/usr/lib/node_modules/tallyarbiter/node_modules/fmerge/install.js:19:4)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: 'fmerge.min.js'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fmerge@1.2.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fmerge@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-11T14_55_18_122Z-debug.log
pi@tallyarbiter:~/tallyarbiter $ tallyarbiter
-bash: tallyarbiter: command not found
pi@tallyarbiter:~/tallyarbiter $ npm start

> tallyarbiter@2.0.10 start /home/pi/tallyarbiter
> node index.js

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'packet'
Require stack:
- /home/pi/tallyarbiter/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/tallyarbiter/index.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/tallyarbiter/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tallyarbiter@2.0.10 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tallyarbiter@2.0.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-08-11T14_56_07_293Z-debug.log
pi@tallyarbiter:~/tallyarbiter $`

This is with Node version 14.17.0 and npm version 6.14.13. Other versions give the same result.

### Version

version pull at 11-08-2021

### Distribution

CLI

### OS

Linux

**Comment by MatteoGheza** [comment]
I can't replicate the bug.
Can you try `sudo npm install -g --unsafe-perm=true --allow-root tallyarbiter`

**Comment by MatteoGheza** [comment]
Else, if it isn't working, can you try to download TallyArbiter from source and run `npm install` then `npm start`

**Comment by josephdadams** [comment]
@peterfdej let us know if the suggested command doesn’t help. You can re open this issue if needed.

**Comment by peterfdej** [comment]
The install command worked. Thx.
