### ISSUE TITLE
[Bug]: OBS Renaming Source crashes TallyArbiter

### ISSUE THREAD

**Issue by hrueger** [josephdadams/TallyArbiter#188]
### What happened?

I renamed the Source in OBS while the `Edit Sources` window was open. That crashed TallyArbiter.

### Version

2.0.13

### Distribution

Source

### OS

Windows

### TallyArbiter configuration

```javascript
{
  "security": {
    "username_settings": "admin",
    "password_settings": "12345",
    "username_producer": "producer",
    "password_producer": "12345"
  },
  "sources": [
    {
      "data": {
        "port": 4000
      },
      "name": "TestSource",
      "sourceTypeId": "05d6bce1",
      "reconnect": true,
      "enabled": true,
      "id": "c580b234",
      "connected": true
    },
    {
      "data": {
        "ip": "127.0.0.1",
        "port": 4444,
        "password": "password"
      },
      "name": "OBS",
      "sourceTypeId": "4eb73542",
      "reconnect": true,
      "enabled": true,
      "id": "7ec865f7",
      "connected": true
    }
  ],
  "devices": [
    {
      "name": "A",
      "enabled": true,
      "id": "c5f78303",
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "B",
      "enabled": true,
      "id": "27a27d99",
      "linkedProgram": false,
      "linkedPreview": false
    }
  ],
  "device_sources": [
    {
      "deviceId": "c5f78303",
      "sourceIdx": "1",
      "rename": true,
      "address": "Szene",
      "sourceId": "7ec865f7",
      "id": "06aa7229"
    }
  ],
  "device_actions": [],
  "tsl_clients": [],
  "tsl_clients_1secupdate": false,
  "cloud_destinations": [],
  "cloud_keys": [],
  "bus_options": [
    {
      "id": "e393251c",
      "label": "Preview",
      "type": "preview",
      "color": "#3fe481",
      "priority": 50
    },
    {
      "id": "334e4eda",
      "label": "Program",
      "type": "program",
      "color": "#e43f5a",
      "priority": 200
    },
    {
      "id": "12c8d698",
      "label": "Preview + Program",
      "type": "previewprogram",
      "color": "#ffc107",
      "priority": 201
    },
    {
      "id": "12c8d699",
      "label": "Aux 1",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    },
    {
      "id": "12c8d689",
      "label": "Aux 2",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    }
  ]
}
```

### Relevant log output

```shell
[29.8.2021, 17:58:39] Loading the stored Tally Arbiter configuration file.
[29.8.2021, 17:58:39] Tally Arbiter Bus Options loaded.
[29.8.2021, 17:58:39] 5 Busses configured.
[29.8.2021, 17:58:39] Tally Arbiter Sources loaded.
[29.8.2021, 17:58:39] 2 Sources configured.
[29.8.2021, 17:58:39] Tally Arbiter Devices loaded.
[29.8.2021, 17:58:39] 2 Devices configured.
[29.8.2021, 17:58:39] Tally Arbiter Device Sources loaded.
[29.8.2021, 17:58:39] Tally Arbiter Device Actions loaded.
[29.8.2021, 17:58:39] Tally Arbiter TSL Clients loaded.
[29.8.2021, 17:58:39] TSL Clients 1 Second Updates are turned off.
[29.8.2021, 17:58:39] Tally Arbiter Cloud Destinations loaded.
[29.8.2021, 17:58:39] Tally Arbiter Cloud Keys loaded.
[29.8.2021, 17:58:39] Initiating Setup for Source: TestSource. Type: Open Sound Control (OSC)
[29.8.2021, 17:58:39] Source: TestSource  Creating new OSC connection.
[29.8.2021, 17:58:39] Initiating Setup for Source: OBS. Type: OBS Studio
[29.8.2021, 17:58:39] Source: OBS  Creating OBS Websocket connection.
[29.8.2021, 17:58:39] Source Setup Complete.
[29.8.2021, 17:58:39] Initializing Device States.
[29.8.2021, 17:58:39] Device States Initialized.
[29.8.2021, 17:58:39] Setting up the REST API.
[29.8.2021, 17:58:39] REST API Setup Complete.
[29.8.2021, 17:58:39] Starting socket.IO Setup.
[29.8.2021, 17:58:39] Socket.IO Setup Complete.
[29.8.2021, 17:58:39] Starting OSC Setup.
[29.8.2021, 17:58:39] Starting VMix Emulation Service.
[29.8.2021, 17:58:39] Starting HTTP Server.
[29.8.2021, 17:58:39] Source: TestSource  OSC port 4000 ready.
[29.8.2021, 17:58:39] OSC Sending Port Ready. Broadcasting on Port: 5958
[29.8.2021, 17:58:39] Finished VMix Emulation Setup. Listening for VMix Tally Connections on TCP Port 8099.
[29.8.2021, 17:58:39] Tally Arbiter running on port 4455
[29.8.2021, 17:58:39] Source: OBS  OBS Connection opened.
[29.8.2021, 17:58:39] OBS Tally Source: 7ec865f7 Added new source: {{STREAMING}}
[29.8.2021, 17:58:39] OBS Tally Source: 7ec865f7 Added new source: {{RECORDING}}
[29.8.2021, 17:58:39] Source: OBS  OBS Authenticated.
[29.8.2021, 17:59:01] Config file saved to disk.
[29.8.2021, 17:59:02] Config file saved to disk.
[29.8.2021, 17:59:21] Source: OBS  Source renamed
[29.8.2021, 17:59:21] Caught exception: TypeError: Cannot set property 'label' of undefined
```

### Error stacktrace (if applicable)

```shell
TypeError: Cannot set property 'label' of undefined
    at renameOBSSource (C:\Users\Hannes\Desktop\Angular\TallyArbiter\index.js:3409:38)
    at OBSWebSocket.<anonymous> (C:\Users\Hannes\Desktop\Angular\TallyArbiter\index.js:3331:25)
    at OBSWebSocket.emit (events.js:375:28)
    at OBSWebSocket.Socket.emit (C:\Users\Hannes\Desktop\Angular\TallyArbiter\node_modules\obs-websocket-js\lib\Socket.js:18:20)
    at WebSocket._socket.onmessage (C:\Users\Hannes\Desktop\Angular\TallyArbiter\node_modules\obs-websocket-js\lib\Socket.js:121:16)
    at WebSocket.onMessage (C:\Users\Hannes\Desktop\Angular\TallyArbiter\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:375:28)
    at Receiver.receiverOnMessage (C:\Users\Hannes\Desktop\Angular\TallyArbiter\node_modules\ws\lib\websocket.js:835:20)
    at Receiver.emit (events.js:375:28)
    at Receiver.dataMessage (C:\Users\Hannes\Desktop\Angular\TallyArbiter\node_modules\ws\lib\receiver.js:437:14)
```

**Comment by JTF4** [comment]
Huh. So for some reason it seems like when it goes to set the label it's not getting the source id passed to it (hence the undefined). I'll have to look at that and see what's happening in detail.

**Comment by josephdadams** [comment]
I've also found if you rename scenes or whatever you can pretty easily get TA to get confused with OBS sources and have one be stuck in PGM until a restart of TA.

**Comment by josephdadams** [comment]
@MatteoGheza can close?
