### ISSUE TITLE
[Bug] TypeError: Cannot read property 'UhQoBVtzZtBkHQFpAAAB' of undefined

### ISSUE THREAD

**Issue by MatteoGheza** [josephdadams/TallyArbiter#191]
### What happened?

If you try to add localhost as a cloud destination (for example: open the page served by Angular serve, localhost:4200, and add 127.0.0.1 and port 4455 with a correct key as cloud destination), `io.sockets.connected` for some reason will be `undefined`, so `io.sockets.connected[cloud_clients[i].socketId]` throws an error.
This code is used in other functions, so it could cause errors in other functions, for example "Tally Client Flash".

### Version

2.0.14

### Distribution

Source

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### TallyArbiter configuration

```javascript
{
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "security": {
    "username_settings": "admin",
    "password_settings": "12345",
    "username_producer": "producer",
    "password_producer": "12345"
  },
  "sources": [],
  "devices": [],
  "device_sources": [
    {
      "deviceId": "1189fe03",
      "sourceIdx": "0",
      "address": "name",
      "sourceId": "TEST",
      "id": "df7466b9"
    }
  ],
  "device_actions": [],
  "tsl_clients": [
    {
      "id": "14122439",
      "ip": "192.168.1.1",
      "port": 1234,
      "transport": "tcp"
    }
  ],
  "tsl_clients_1secupdate": true,
  "cloud_destinations": [],
  "cloud_keys": []
}
```

### Relevant log output

```shell
[30/8/2021, 22:35:27] Loading the stored Tally Arbiter configuration file.
[30/8/2021, 22:35:27] Tally Arbiter Sources loaded.
[30/8/2021, 22:35:27] 0 Sources configured.
[30/8/2021, 22:35:27] Tally Arbiter Devices loaded.
[30/8/2021, 22:35:27] 0 Devices configured.
[30/8/2021, 22:35:27] Tally Arbiter Device Sources loaded.
[30/8/2021, 22:35:27] Tally Arbiter Device Actions loaded.
[30/8/2021, 22:35:27] Tally Arbiter TSL Clients loaded.
[30/8/2021, 22:35:27] TSL Clients 1 Second Updates are turned on.
[30/8/2021, 22:35:27] Starting TSL Clients 1 Second Interval.
[30/8/2021, 22:35:27] Tally Arbiter Cloud Destinations loaded.
[30/8/2021, 22:35:27] Tally Arbiter Cloud Keys loaded.
[30/8/2021, 22:35:27] Source Setup Complete.
[30/8/2021, 22:35:27] Initializing Device States.
[30/8/2021, 22:35:27] Device States Initialized.
[30/8/2021, 22:35:27] Setting up the REST API.
[30/8/2021, 22:35:27] REST API Setup Complete.
[30/8/2021, 22:35:27] Starting socket.IO Setup.
[30/8/2021, 22:35:27] Socket.IO Setup Complete.
[30/8/2021, 22:35:27] Starting OSC Setup.
[30/8/2021, 22:35:27] Starting VMix Emulation Service.
[30/8/2021, 22:35:27] Initiating 1 TSL Client Connections.
[30/8/2021, 22:35:27] TSL Client: 192.168.1.1:1234 (tcp)
[30/8/2021, 22:35:27] TSL Client: 14122439  Initiating TSL Client TCP Socket.
[30/8/2021, 22:35:27] Finished TSL Client Connections.
[30/8/2021, 22:35:27] Initiating 1 Cloud Destination Connections.
[30/8/2021, 22:35:27] Cloud Destination: 127.0.0.1:4455
[30/8/2021, 22:35:27] Cloud Destination: 127.0.0.1:4455  Initiating Connection.
[30/8/2021, 22:35:27] Finished Cloud Destinations.
[30/8/2021, 22:35:27] Starting HTTP Server.
[30/8/2021, 22:35:27] OSC Sending Port Ready. Broadcasting on Port: 5958
[30/8/2021, 22:35:27] Finished VMix Emulation Setup. Listening for VMix Tally Connections on TCP Port 8099.
[30/8/2021, 22:35:27] Tally Arbiter running on port 4455
[30/8/2021, 22:35:28] Cloud Destination: 127.0.0.1:4455 Connected. Sending Initial Data.
[30/8/2021, 22:35:28] Cloud Client Connected: ::ffff:127.0.0.1
[30/8/2021, 22:35:49] An error occurred with the connection to 192.168.1.1:1234  Error: connect ETIMEDOUT 192.168.1.1:1234
[30/8/2021, 22:35:49] TSL Client 14122439 Connection Closed: 192.168.1.1:1234
[30/8/2021, 22:37:20] Cloud Key Deleted: ciao
[30/8/2021, 22:37:20] Config file saved to disk.
[30/8/2021, 22:37:32] Caught exception: TypeError: Cannot read property 'UhQoBVtzZtBkHQFpAAAB' of undefined
```

### Error stacktrace (if applicable)

```shell
TypeError: Cannot read property 'UhQoBVtzZtBkHQFpAAAB' of undefined
    at TallyArbiter_Remove_Cloud_Client (C:\Users\ardui\progetti\TallyArbiter-4\index.js:6856:28)
    at TallyArbiter_Manage (C:\Users\ardui\progetti\TallyArbiter-4\index.js:5670:14)
    at Socket.<anonymous> (C:\Users\ardui\progetti\TallyArbiter-4\index.js:1667:15)
    at Socket.emit (events.js:375:28)
    at Socket.emitUntyped (C:\Users\ardui\progetti\TallyArbiter-4\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\ardui\progetti\TallyArbiter-4\node_modules\socket.io\dist\socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by MatteoGheza** [comment]
@josephdadams sorry, I forgot to say that I'm working on this.
Can you please review my PR?

**Comment by blakecarrasco** [comment]
Just wanted to let you guys know that this update worked well, and our tally system had no issues during production.  I appreciate the help. Thanks.
