### ISSUE TITLE
New Install is missing module 'Packet"

### ISSUE THREAD

**Issue by WesleyvN** [josephdadams/TallyArbiter#25]
Hi all, 

I have installed a new Raspberry to use the TallyArbiter code. But after the install im run the code `node index.js`(at the installed directory) and the following is showing up on the terminal:

`pi@TallyServer:~/tallyarbiter $ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'packet'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/tallyarbiter/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

and i have downloaded it directly from GitHub by using this ommand (`git clone https://github.com/josephdadams/tallyarbiter `)

Im using the Raspberry pi 3B as Server 
Node JS version V10.21.0
NPM version V6.14.8

Can somebody explain/help me to fix this?

Thanks in advance, Wesley

**Comment by guido-visser** [comment]
You should run `npm install` before executing `node server.js`. Does that fix your issue?

**Comment by WesleyvN** [comment]
Hi Guido,

Thanks for your help! Indeed i have forgot to install the npm!
