### ISSUE TITLE
[Bug] Error: bind EADDRINUSE 0.0.0.0:9800

### ISSUE THREAD

**Issue by isaiahfranco** [josephdadams/TallyArbiter#306]
### What happened?

A bug happened!

### Version

2.0.16

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### TallyArbiter configuration

```javascript
{
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "security": {
    "username_settings": "admin",
    "password_settings": "12345",
    "username_producer": "producer",
    "password_producer": "12345"
  },
  "sources": [
    {
      "data": {
        "port": 9800,
        "transport_type": "udp"
      },
      "name": "Carbonite",
      "sourceTypeId": "039bb9d6",
      "reconnect": true,
      "enabled": true,
      "id": "4a400ded",
      "connected": true
    }
  ],
  "devices": [
    {
      "name": "Cam 1",
      "description": "PTZ",
      "enabled": true,
      "id": "7948cb9e",
      "linkedProgram": false,
      "tslAddress": 1,
      "linkedPreview": false
    },
    {
      "name": "Cam 2 (FOH 1)",
      "description": "Hitachi Z-HD5000",
      "enabled": true,
      "id": "f2a1fcf8",
      "tslAddress": 2,
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "Cam 3 (FOH 2)",
      "description": "Hitachi Z-HD5500",
      "enabled": true,
      "id": "1786a748",
      "tslAddress": 3,
      "linkedPreview": false,
      "linkedProgram": false
    },
    {
      "name": "Cam 4 (Jib)",
      "description": "Hitachi Z-HD5000",
      "tslAddress": 4,
      "enabled": true,
      "id": "27c946b4",
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "Cam 5",
      "description": "Stage Cam 1",
      "enabled": true,
      "id": "99bf85ea",
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "Cam 6",
      "description": "Stage Cam 2",
      "enabled": true,
      "id": "e317f486",
      "linkedPreview": false,
      "linkedProgram": false
    },
    {
      "name": "Cam 7",
      "enabled": true,
      "id": "cdd75f64"
    },
    {
      "name": "Cam 8",
      "enabled": true,
      "id": "b1de9786"
    },
    {
      "name": "Pro1",
      "enabled": true,
      "id": "45c07ca8",
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "Pro2",
      "enabled": true,
      "id": "d755d60a",
      "linkedProgram": false,
      "linkedPreview": false
    },
    {
      "name": "Key 1",
      "enabled": true,
      "id": "d3aed640",
      "linkedPreview": false,
      "linkedProgram": false,
      "tslAddress": 27
    }
  ],
  "device_sources": [],
  "device_actions": [],
  "tsl_clients": [],
  "tsl_clients_1secupdate": false,
  "cloud_destinations": [],
  "cloud_keys": []
}
```

### Relevant log output

```shell
[12/16/2021, 11:53:23 AM] Loading the stored Tally Arbiter configuration file.
[12/16/2021, 11:53:23 AM] Tally Arbiter Sources loaded.
[12/16/2021, 11:53:23 AM] 0 Sources configured.
[12/16/2021, 11:53:23 AM] Tally Arbiter Devices loaded.
[12/16/2021, 11:53:23 AM] 11 Devices configured.
[12/16/2021, 11:53:23 AM] Tally Arbiter Device Sources loaded.
[12/16/2021, 11:53:23 AM] Tally Arbiter Device Actions loaded.
[12/16/2021, 11:53:23 AM] Tally Arbiter TSL Clients loaded.
[12/16/2021, 11:53:23 AM] TSL Clients 1 Second Updates are turned off.
[12/16/2021, 11:53:23 AM] Tally Arbiter Cloud Destinations loaded.
[12/16/2021, 11:53:23 AM] Tally Arbiter Cloud Keys loaded.
[12/16/2021, 11:53:23 AM] Source Setup Complete.
[12/16/2021, 11:53:23 AM] Initializing Device States.
[12/16/2021, 11:53:23 AM] Device States Initialized.
[12/16/2021, 11:53:23 AM] Setting up the REST API.
[12/16/2021, 11:53:23 AM] REST API Setup Complete.
[12/16/2021, 11:53:23 AM] Starting socket.IO Setup.
[12/16/2021, 11:53:23 AM] Socket.IO Setup Complete.
[12/16/2021, 11:53:23 AM] Starting OSC Setup.
[12/16/2021, 11:53:23 AM] Starting VMix Emulation Service.
[12/16/2021, 11:53:23 AM] Starting HTTP Server.
[12/16/2021, 11:53:23 AM] OSC Sending Port Ready. Broadcasting on Port: 5958
[12/16/2021, 11:53:23 AM] Finished VMix Emulation Setup. Listening for VMix Tally Connections on TCP Port 8099.
[12/16/2021, 11:53:23 AM] Tally Arbiter running on port 4455
[12/16/2021, 11:53:51 AM] Source Added: Carbonite
[12/16/2021, 11:53:51 AM] Source: Carbonite  Creating Ross Carbonite UDP Connection.
[12/16/2021, 11:53:51 AM] Source: Carbonite  Ross Carbonite Server started. Listening for data on UDP Port: 9800
[12/16/2021, 11:53:51 AM] Config file saved to disk.
[12/16/2021, 11:53:51 AM] Caught exception: Error: bind EADDRINUSE 0.0.0.0:9800
```

### Error stacktrace (if applicable)

```shell
Error: bind EADDRINUSE 0.0.0.0:9800
    at dgram.js:337:20
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by josephdadams** [comment]
What else are you running on this machine that’s using port 9800? Can you just pick a different port?

**Comment by isaiahfranco** [comment]
Turns out a restart of the computer fixed it. Imagine that!
