### ISSUE TITLE
[Bug]: Blinkt listener not working

### ISSUE THREAD

**Issue by Mo96M** [josephdadams/TallyArbiter#395]
### What happened?

I tried to install the Blinkt listener on a raspberry pi zero. When starting the code an error appears about the missing module "zeroconf"

### Version

3.0.1

### Distribution

CLI

### OS

Linux

### If applicable, What Listener Clients are You Using?

Blinkt

### Relevant log output

```shell
pi@pitallyclient:~ $ sudo python3 pimoroni-blinkt-listener.py 192.168.0.19 4455
Traceback (most recent call last):
  File "/home/pi/pimoroni-blinkt-listener.py", line 15, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
ModuleNotFoundError: No module named 'zeroconf'
```

**Comment by JTF4** [comment]
Try running `pip install zeroconf`

**Comment by JTF4** [comment]
@Mo96M were you able to try that command?

**Comment by Mo96M** [comment]
@JTF4 yes it worked kind of. Here is the command line output:

`pi@pitallyclient:~ $ sudo python3 pimoroni-blinkt-listener.py 192.168.0.19 4455
usage: pimoroni-blinkt-listener.py [-h] [--host HOST] [--port PORT]
                                   [--device-id DEVICE_ID] [--debug]
                                   [--disable-reassign] [--disable-flash]
                                   [--skip-blinkt]
pimoroni-blinkt-listener.py: error: unrecognized arguments: 192.168.0.19 4455

pi@pitallyclient:~ $ sudo python3 pimoroni-blinkt-listener.py --host 192.168.0.19 --port 4455
Exception in thread zeroconf-ServiceBrowser-_tally-arbiter._tcp-566:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_services/browser.py", line 532, in run
    self._fire_service_state_changed_event(event)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_services/browser.py", line 416, in _fire_service_state_changed_event
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_services/__init__.py", line 55, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_services/browser.py", line 177, in on_change
    getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
  File "/home/pi/pimoroni-blinkt-listener.py", line 319, in add_service
    server_uuid = info.properties.get(b"uuid").decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'properties'
`

But now there's a new error.

**Comment by JTF4** [comment]
I did some further research and it appears that I really need to update the docs on this one.

See if running `pip3 install zeroconf` helps at all.

**Comment by josephdadams** [comment]
@Mo96M did you get it working after following the instructions?
