### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by BenJamesAndo** [josephdadams/TallyArbiter#456]
### What happened?

I'm running OBS with 2 M5 Atoms. On my home computer it ran perfectly with no errors. Now when I run it at work it has the following errors. I did figure out how to have it not through errors. I had to disable some macros in Advanced Scene Switcher, which are unique to the work computer. Below is a screenshot of one of the macros. If I only run 'Cam 1 Border' macro then it's fine. But as soon as I enable 2 or more of these macros, Tally Arbiter starts throwing these errors. My best guess is that Adcanced Scene switcher is modifying some filters on a source that somewhat interacts with the source that Tally Arbiter is looking at. Perhaps it throws it off somehow. The tally lights do work, but sometimes I have to restart Tally Arbiter to get them working properly. Other times it doesn't work properly.
![image](https://user-images.githubusercontent.com/44917135/173502500-827fa14f-227b-4720-83f7-4c381e9aa67b.png)

### Version

3.0.4

### Distribution

Desktop

### OS

Windows

### What browsers are you seeing the problem on?

Chrome

### If applicable, What Listener Clients are You Using?

M5 Stick

### TallyArbiter configuration

```javascript
{
  "security": {
    "jwt_private_key": ""
  },
  "users": [],
  "device_actions": [],
  "device_sources": [
    {
      "deviceId": "14856c5d",
      "sourceIdx": "0",
      "address": "Cam 1",
      "sourceId": "2df5890d",
      "id": "39f35330"
    },
    {
      "deviceId": "14856c5d",
      "sourceIdx": "0",
      "address": "Cam 1",
      "sourceId": "2df5890d",
      "id": "17b4c117"
    },
    {
      "deviceId": "04a414f3",
      "sourceIdx": "0",
      "address": "Cam 2",
      "sourceId": "2df5890d",
      "id": "c5922be6"
    }
  ],
  "devices": [
    {
      "name": "Cam 1",
      "description": "",
      "enabled": true,
      "id": "14856c5d"
    },
    {
      "name": "Cam 2",
      "enabled": true,
      "id": "04a414f3"
    },
    {
      "name": "Cam 4",
      "enabled": true,
      "id": "4841a0e9"
    }
  ],
  "sources": [
    {
      "data": {
        "ip": "127.0.0.1",
        "port": 4444
      },
      "name": "OBS",
      "sourceTypeId": "4eb73542",
      "reconnect": true,
      "enabled": true,
      "id": "2df5890d",
      "max_reconnects": 5,
      "connected": true
    }
  ],
  "bus_options": [
    {
      "id": "e393251c",
      "label": "Preview",
      "type": "preview",
      "color": "#3ff13b",
      "priority": 50
    },
    {
      "id": "334e4eda",
      "label": "Program",
      "type": "program",
      "color": "#e43f5a",
      "priority": 200
    },
    {
      "id": "12c8d699",
      "label": "Aux 1",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    },
    {
      "id": "12c8d689",
      "label": "Aux 2",
      "type": "aux",
      "color": "#0000FF",
      "priority": 100
    }
  ],
  "externalAddress": "http://0.0.0.0:4455/#/tally",
  "remoteErrorReporting": false,
  "uuid": ""
}
```

### Relevant log output

```shell
[2022-06-10 18:32:52] info: Listener Client Connected. Type: m5Atom-103243307566412 Device: Cam 2
[2022-06-10 18:32:52] info: Sending device states to Listener Client: 5bc0d488 - Cam 1
[2022-06-10 18:32:52] info: Sending device states to Listener Client: 93d06115 - Cam 2
[2022-06-10 18:33:55] error: Caught exception: TypeError: Cannot read properties of undefined (reading 'includes')
```

### Error stacktrace (if applicable)

```shell
TypeError: Cannot read properties of undefined (reading 'includes')
    at OBSWebSocket.<anonymous> (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\dist\sources\OBS.js:253:39)
    at OBSWebSocket.emit (node:events:390:28)
    at OBSWebSocket.Socket.emit (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\obs-websocket-js\lib\Socket.js:18:20)
    at WebSocket._socket.onmessage (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\obs-websocket-js\lib\Socket.js:121:16)
    at WebSocket.onMessage (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\ws\lib\websocket.js:983:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (C:\Users\GCTV-Livestream\AppData\Local\Programs\tallyarbiter\resources\app.asar\node_modules\ws\lib\receiver.js:435:17)
```

**Comment by josephdadams** [comment]
Closing this as stale - it was reported against 3.0.4 and the code paths in the traceback have since been rewritten with defensive guards, so the reported error should no longer occur.

One thing worth noting from the config you posted: it contains two device_sources entries with the same deviceId, sourceId and address (39f35330 and 17b4c117, both 'Cam 1'). That duplicate would have made the device's bus arbitration behave unpredictably. If you still see problems on a current version, please reopen with a fresh stack trace and I will take another look.
