### ISSUE TITLE
[Bug]: Docker image for linux/arm64 broken (missing freetype2 prebuilds)

### ISSUE THREAD

**Issue by peschuster** [josephdadams/TallyArbiter#683]
### What happened?

The current docker image for linux/arm64 is broken, because the freetype2 module has no prebuild binding for linux-arm64-musl (the libc of alpine).

The error message in the container log is:

```
Error: Failed to find binding for freetype2
    at loadBinding (/app/node_modules/pkg-prebuilds/bindings.js:96:27)
    at Object.<anonymous> (/app/node_modules/@julusian/freetype2/index.js:3:51)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/app/node_modules/atem-connection/dist/lib/multiviewLabel.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
```

I debugged the container and node is trying to load `/app/node_modules/@julusian/freetype2/prebuilds/freetype2-linux-arm64-musl/node-napi-v7.node` which does not exist.

The following change fixes the bug, but I am not sure whether this is the preferred/best solution:

```diff
diff --git a/Dockerfile b/Dockerfile
index 114106a..9920109 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -9,6 +9,9 @@ RUN apk add --update nodejs npm \
     && npm i --ignore-script --omit=dev \
     && npm uninstall bcryptjs \
     && npm install bcryptjs \
+    && cd node_modules/@julusian/freetype2 \
+    && node-gyp rebuild \
+    && cd ../../../ \
     && npm uninstall node-gyp -g \
     && apk del .build-deps
```

### Version

v3.0.10

### Distribution

Docker

### OS

Linux

**Comment by josephdadams** [comment]
Works for me, pr?
